### ISSUE TITLE
NO

### ISSUE THREAD

**Issue by DanBaDo** [MiguelUbeda/todo-fetch#1]
Repite conmigo: las lineas no se salen de la pantalla, las lineas no se salen de la pantalla, las lineas no se salen de la pantalla, las lineas no se salen de la pantalla, las lineas no se salen de la pantalla, las lineas no se salen de la pantalla, las lineas no se salen de la pantalla, las lineas no se salen de la pantalla, las lineas no se salen de la pantalla, las lineas no se salen de la pantalla, las lineas no se salen de la pantalla...

https://github.com/MiguelUbeda/todo-fetch/blob/8a0259899bb6439e8c5ca39a2636ce31c518c3ea/src/js/component/input.jsx#L44

**Comment by MiguelUbeda** [comment]
Arreglado Dani! Gracias por el feedback, ya he reenviado el proyecto
